//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wynges.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquiler
    {
        public Alquiler()
        {
            this.AlquilerDetalle = new HashSet<AlquilerDetalle>();
        }
    
        public int AlquilerId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Descuento { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Impuesto { get; set; }
        public decimal Total { get; set; }
        public string Estado { get; set; }
        public int ClienteClienteId { get; set; }
    
        public virtual ICollection<AlquilerDetalle> AlquilerDetalle { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
