//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wynges.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlquilerDetalle
    {
        public int AlquilerDetalleId { get; set; }
        public decimal Precio { get; set; }
        public string FechaDevolucion { get; set; }
        public int PeliculaPeliculaId { get; set; }
        public int AlquilerAlquilerId { get; set; }
    
        public virtual Pelicula Pelicula { get; set; }
        public virtual Alquiler Alquiler { get; set; }
    }
}
