//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wynges.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public Pelicula()
        {
            this.AlquilerDetalle = new HashSet<AlquilerDetalle>();
        }
    
        public int PeliculaId { get; set; }
        public string Nombre { get; set; }
        public string Genero { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<AlquilerDetalle> AlquilerDetalle { get; set; }
    }
}
