//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wynges.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WyngesModelContainer : DbContext
    {
        public WyngesModelContainer()
            : base("name=WyngesModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> ClienteSet { get; set; }
        public DbSet<Pelicula> PeliculaSet { get; set; }
        public DbSet<Alquiler> AlquilerSet { get; set; }
        public DbSet<AlquilerDetalle> AlquilerDetalleSet { get; set; }
    }
}
